name = "Tyler"
uuid = "e170d443-b9d6-418a-9ee8-061e966341ef"
authors = ["SimonDanisch <sdanisch@gmail.com>", "Lazaro Alonso <lazarus.alon@gmail.com>", "Martijn Visser <mgvisser@gmail.com>", "Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.4"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MapTiles = "fea52e5a-b371-463b-85f5-81770daa2737"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ThreadSafeDicts = "4239201d-c60e-5e0a-9702-85d713665ba7"
TileProviders = "263fe934-28e1-4ae9-998a-c2629c5fede6"

[compat]
Colors = "0.12"
Extents = "0.1.2"
GeoInterface = "1"
GeometryBasics = "0.4"
HTTP = "1"
LRUCache = "1"
LinearAlgebra = "1"
Makie = "0.20, 0.21"
MapTiles = "1"
OrderedCollections = "1"
ThreadSafeDicts = "0.1"
TileProviders = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
